name: 'Python test'
description: 'test a python script'
inputs:
  who-to-greet:  
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'the time we greeted!'
runs:
  using: 'Docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
  # using: "composite"
  # steps:
  #   - run: cd $GITHUB_WORKSPACE &&
  #          git clone https://github.com/Chandolkar001/test_github_actions.git &&
  #          cd test_github_actions &&
  #          mkdir actions
  #     shell: bash
  #   - name: setup python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: 3.9
  #   - name: Install Dependencies
  #     run: python -m pip install --upgrade pip &&
  #          pip install -r test_github_actions/requirements.txt
  #     shell: bash
  #   - uses: actions/checkout@v4
  #     with:
  #       path: 'test_github_actions/actions/'
  #   - name: Secret testing
  #     run: cd $GITHUB_WORKSPACE && cd test_github_actions && python3 test.py
  #     shell: bash

