name: 'Python test'
description: 'test a python script'
inputs:
  who-to-greet:  
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'the time we greeted!'
runs:
  using: 'Docker'
  image: 'Dockerfile'
  args:
    - "-a ${{ inputs.who-to-great }}"


