name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:
    description: ""
    required: true
    default: "secret-scan"
  github-context:
    description: ""
    required: true
    default: ""
  auth-token:
    description: ""
    required: true
    default: ""
  api-endpoint:
    description: ""
    required: true
    default: ""
  debug:
    description: ""
    required: false
    default: "false"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-a${{ inputs.who-to-greet }}"
    - "-b${{ inputs.github-context }}"
    - "-c${{ inputs.auth-token }}"
    - "-d${{ inputs.api-endpoint }}"
    - "-e${{ inputs.debug }}"
