name: 'test action metadata'
description: 'Greet someone'
inputs:
  who-to:
    description: 'who to greet?'
    required: true
    default: 'World'
outputs:
  random-num:
  description: "outputs a random number"
  value: ${{ steps.random-num-gen.outputs.random-num }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to }}.
      shell: bash
    - id: random-num-gen
      run: echo "random-num=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash