name: Check on push
run-name: ${{ github.actor }} has pushed
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: actions/test_github_actions@v1
        with:
          who-to: 'Tron'
      - run: echo random-num ${{ steps.foo.outputs.random-num }}
        shell: bash